### ISSUE TITLE
HeaderBar gives error when using stock react

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2-ui#105]
onTouchTap does not exist in stock React.

**Comment by harsh-a1** [comment]
![header bar issue screenshot from 2017-02-16 21 31 31](https://cloud.githubusercontent.com/assets/1791655/23029160/9a0d30ac-f48f-11e6-8a3a-c56dcc6a56ce.png)

**Comment by varl** [comment]
Headerbar is now a standalone component, check out how to use it in the examples-app built with CRA in this repo: https://github.com/dhis2/d2-ui/blob/master/examples/create-react-app/src/components/header-bar.js
