### ISSUE TITLE
HeaderBar gives error when using create-react-app

### ISSUE THREAD

**Issue by mjames21** [dhis2/d2-ui#122]
![h2-ui](https://user-images.githubusercontent.com/11080309/31347724-c9f3b152-ad0c-11e7-9abf-d67e79d6d815.png)

**Comment by danse** [comment]
a DuckDuckGo search yields this https://stackoverflow.com/a/41045716/393758 which seems relevant. Maybe you have to wrap the toolbar in the Material UI theme provider

**Comment by varl** [comment]
@mjames21, are you wrapping your application component in a `MUIProvider`?

E.g.
```js
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';

<MuiThemeProvider muiTheme={getMuiTheme()}>
    <AppWithMaterialUIComponents />
</MuiThemeProvider>
```

**Comment by varl** [comment]
Headerbar is not a standalone component, check out how to use it in the examples-app built with CRA in this repo: https://github.com/dhis2/d2-ui/blob/master/examples/create-react-app/src/components/header-bar.js
