### ISSUE TITLE
DHIS2 versioning with lerna packages

### ISSUE THREAD

**Issue by SferaDev** [dhis2/d2-ui#262]
We are starting to use d2 and d2-ui on several projects at UPC and we find some of our documentation is outdated or missing regarding usage of the dependencies on older DHIS2 versions.

We're using 2.28 on our instances but installing latest version of the npm packages shows newer UI interface. We would like to know how to match 2.28 with the lerna release tag (ie 1.2.0 for d2-ui-core).

If it's not possible right now to match older DHIS2 UI styling with the lerna packages it should be noted somehow on the README. I also find that it would be a good option to match the visual UI with the d2 version and allow back-compat when possible, but that might be harder to implement.

An example of some of our dependencies:

```
        "@dhis2/d2-ui-app": "^1.0.5",
        "@dhis2/d2-ui-core": "^1.2.0",
        "@dhis2/d2-ui-header-bar": "^1.1.1",
        "d2": "^28.0.0"
```

Thank you for your time and good work,

Alexis Rico
WISCENTD-UPC

**Comment by varl** [comment]
Hi @SferaDev 

Sorry about this information not being available anywhere but to use 2.28 or 2.29 of d2-ui you need to fallback to a different set of packages: https://www.npmjs.com/package/d2-ui/v/29.0.29

For 2.30 we started looking into how we can make it easier to install just the parts needed from d2-ui and came up with a Lerna-based approach. We are not entirely happy with how it works, but I have duly noted that we need to document a migration path more clearly.

For 2.29 your `package.json` would be:

```
"d2": "^28.0.0",
"d2-ui": "^28.0.0"
```

and for 2.29:

```
"d2": "^29.0.0",
"d2-ui": "^29.0.0"
```

Cheers
