### ISSUE TITLE
Group editor will always keep spinning if there are no available values

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2-ui#27]
Start dhis2 on an empty database and open the dataElement edit screen.

**Comment by VaughanJackson** [comment]
@Markionium 
Is this the same behaviour as is seen in the D2-UI GroupEditor component example?

**Comment by Markionium** [comment]
Yes pretty much like that.

This issue is fairly dated so i'm not sure if it's still an issue on an empty database though :)

**Comment by nicolayr** [comment]
Actually this was resolved a long time ago.

The component no longer assumes that no values = loading. If you look at the group editor example there are buttons to "stop loading" and "start loading".

**Comment by VaughanJackson** [comment]
Good news!
