### ISSUE TITLE
Examples Initial setup documentation

### ISSUE THREAD

**Issue by borisrorsvort** [dhis2/d2-ui#276]
It seems that watching the main repo and building the example is not enough to make it work.
Without documentation, I would expect the examples to run with fixtures, but it seems that a local dhis2 instance is required. 
It would be nice to mention it in the readme and point to some documentation on how to set it up.

**Comment by borisrorsvort** [comment]
I also tried to set `REACT_APP_DHIS2_BASE_URL="https://play.dhis2.org/2.29"` but it does not seem to get what it needs to start the examples

**Comment by varl** [comment]
Hi @borisrorsvort 

Yes, you are touching on a core pain of the d2-ui library; that it requires a fully-fledged DHIS2 instance to connect to. Not only that, the API versions has to match and it's generally a pain to figure out and do changes.

If you are using a 2.29 instance, I would recommend using the v29 branch of d2-ui: https://github.com/dhis2/d2-ui/tree/v29

The split into lerna packages happened with 2.30.

I'll update the docs to make it clear, thanks for pointing this out.

Cheers!

**Comment by borisrorsvort** [comment]
@varl thanks for the info. Do you hope at some point have some retro compat api wize? 2.26 -> 2.30 for example?

**Comment by varl** [comment]
@borisrorsvort the d2-ui framework is seriously coupled to the d2 framework which is coupled to the api version, so backwards compatibility is a tricky nut to crack here. One of the things we hoped to accomplish by splitting out into a lerna repo was to do this migration step by step, but that unveiled different problems.

In the long term, we are looking at replacing the core components with our own components (no API deps), doing away with the Material UI dependency, and then de-coupling the complex components from d2 so we can reach the final stage of supporting multiple API versions per component.

The official supported versions are the 3 latest versions, so at the time of writing, we only aim to support 2.28, 2.29, and 2.30. So 2.26 and 2.27 are out of scope and will not be supported.

**Comment by borisrorsvort** [comment]
@varl Thanks. I'm a bit concerned though that you plan to ditch material-ui. Lot's of app builders are now using it extensively for dhis2 apps. It's a major asset in terms of productivity. If dhis2 wants apps to keep some coherence, it would be much harder to only use your components only. Material-ui is in good shape and won't disapear soon. It also now has a stable api. I would be imho a much sensible choice to build upon it rather than reinventing the wheel.
Also dhis2 would benenit from following a bit more the material design guidelines in general.
Don't get me wrong, the work you're doing is awesome and a definite improvement over the past dhis2 versions. But embracing common industry libraries is a big plus for the eco system imho.

**Comment by varl** [comment]
@borisrorsvort i'd be happy to discuss this more in-depth over e-mail: viktor@dhis2.org

>But embracing common industry libraries is a big plus for the eco system imho.

I don't think that the core devs should force any 3rd party libraries on the community, and instead should commit to making sure that the libs we do build our things are light, easy to use, and plugs into whatever the developer wants to use. Be it MUI, MDWC, plain React, or what have you.

>Lot's of app builders are now using it extensively for dhis2 apps.

They can still use it if they wish, nothing is going to break.

>If dhis2 wants apps to keep some coherence, it would be much harder to only use your components only.

Our components can be used where applicable, for the rest, any framework (or none) will do. Our components will not add any overhead except for the JS and CSS they carry. (That is not the situation today.)

>Also dhis2 would benenit from following a bit more the material design guidelines in general.

Hehe, you should talk to our usability designers about that. :)
