### ISSUE TITLE
Color picker component

### ISSUE THREAD

**Issue by nicolayr** [dhis2/d2-ui#30]
We need a component for displaying and changing color settings. Since the colors will be used in both web and Android apps, both 6 and 8 digit hex formats need to be supported (RRGGBB_888 and AARRGGBB_8888).

**Comment by adhbh** [comment]
Does this look good - http://casesandberg.github.io/react-color/ ?

**Comment by nicolayr** [comment]
Yes, that looks great. However it doesn't support the AARRGGBB color format, so we need to add that.

**Comment by Markionium** [comment]
I must say i specifically like the "chrome" one. It's not too complicated and looks like it has everything we need.

![image](https://cloud.githubusercontent.com/assets/2134901/13573253/06a72eb0-e47f-11e5-8480-efdd4fe29039.png)

We could transform the color representation from the RGBA to #AARRGGBB color format. We might have to do that anyways as we can't render #AARRGGBB :)
Perhaps our `<ColorPicker />`  component could wrap this and with our defaults and do the transformation for us. :)

**Comment by nicolayr** [comment]
It's nice, indeed.

However I think it's often easier to pick a nice color if the choices are limited to colors that go well together. For example the **primary** mode could be to choose between a subset of the colors from the [material color palettes](https://www.google.com/design/spec/style/color.html#color-color-palette), while a **secondary** mode could be to fine tune the chosen color for example using the chrome picker.

**Comment by adhbh** [comment]
@nicolayr I am working on this component and as you suggested i am keeping 2 modes - primary and secondary. Does swatches look good to you for primary?
<img width="353" alt="screen shot 2016-03-13 at 3 23 05 am" src="https://cloud.githubusercontent.com/assets/6566723/13725552/fc692e12-e8ca-11e5-9016-18f2e85bdfda.png">

**Comment by adhbh** [comment]
@nicolayr and @Markionium 
Here is the how its coming out. (I have to work more on styling). 
1. First a color swatch is visible and user has to choose a color. This is the primary color.
2. When user chooses a color, a chrome style color picker opens to the right. This lets the user tune the chosen color.

Please let me know if it looks good. Anything to be added/removed?

<img width="1280" alt="screen shot 2016-03-13 at 7 13 08 am" src="https://cloud.githubusercontent.com/assets/6566723/13726389/4dd227de-e8eb-11e5-95e2-c7e415f5bdb8.png">

**Comment by nicolayr** [comment]
Looks good @adhbh !

It sounds like the UX you're going for is not exactly what we need though.

- The default state of the component should be to display only the current color. It also needs to be able to display something useful when there is no current color.
- This default state should not use more space than necessary.
- Once the user interacts with the component, such as by clicking on it, it should display color options.
- It's preferable to display these options in a dialog or a popup, rather than expanding the component inside the page.
- It should be possible to adjust the "swatches" that are displayed by the component using a prop.

Also, the API of the component should essentially act like a text field, so that it can be used as a normal form field. That means that it should respect the `value=` prop, and when the user changes the color it should trigger the `onChange` event handler.

**Comment by adhbh** [comment]
Thanks @nicolayr  :+1: 
i will make the required UX changes as you suggested and open a PR asap.

**Comment by adhbh** [comment]
@nicolayr As you suggested i have made some changes to the UX.  Please let me know what you think about this. 
1. The swatches can be adjusted using the 'colors' prop.
2. The default state now is a single swatch with the selected color.
3. On clicking it, the color-selector opens in a material-ui dialog. The dialog has 3 action buttons- 'cancel', 'fine tune'(only if prop canFineTune is true) and 'select'. 
4. Example: <ColorPicker colors={colors} value={selectedColor} canFineTune = {true} />
5. Support  RRGGBB_888 and AARRGGBB_8888.

Here are the gifs: - 
link: https://cloud.githubusercontent.com/assets/6566723/13752745/371d08e6-ea36-11e5-8967-7a7a51804054.gif
![first1](https://cloud.githubusercontent.com/assets/6566723/13752745/371d08e6-ea36-11e5-8967-7a7a51804054.gif)

link: https://cloud.githubusercontent.com/assets/6566723/13753419/db226646-ea38-11e5-8230-b4bf196c34a6.gif
![second2](https://cloud.githubusercontent.com/assets/6566723/13753419/db226646-ea38-11e5-8230-b4bf196c34a6.gif)

**Comment by adhbh** [comment]
UPDATE- 
@nicolayr I have also added onChange event handler.
I have to do some more work on fine-tune design. Please let me know how do you like the overall design and any changes you would like to suggest?

**Comment by nicolayr** [comment]
@adhbh It's hard to tell without being able to play with the component myself, but it definitely looks like you're on the right track. I'm wondering if perhaps the select color -> click to fine tune flow is a bit more cumbersome than it needs to be? Also, maybe it would be better to use a less intrusive popup instead of a full-blown dialog?

**Comment by adhbh** [comment]
@nicolayr 
As you suggested, I have changed the UI.
<img width="404" alt="screen shot 2016-03-16 at 9 00 09 pm" src="https://cloud.githubusercontent.com/assets/6566723/13818562/529c67e2-ebbc-11e5-96b5-ceb2735cd26b.png">

I have made this component so that it goes well with material-ui library. I have uploaded the code so that you can try the example and suggest changes: https://github.com/adhbh/react-color-selector.git

**Comment by adhbh** [comment]
@nicolayr @Markionium 
Did you get chance to try the [ColorPicker component](https://github.com/adhbh/react-color-selector.git) example? Please let me know what you think. If you think something is missing or should be added. 
If it is good and as per the requirements, I will put this into D2-UI. We can use it for settings-app as well as user-profile-app. I am also planning to add _Chips component_ soon.

**Comment by nicolayr** [comment]
@adhbh I have looked at your component but I haven't had the time to properly review it yet. It's looking very good, but there are some things that we would need to change before we can integrate it into D2-UI. I'll try to find the time to give you proper feedback later today.
