### ISSUE TITLE
HeaderBar re-renders unnecessarily and console.log's about it

### ISSUE THREAD

**Issue by amcgee** [dhis2/d2-ui#300]
The `console.log` calls (both "loading" and "loaded" variants) were introduced in change 92c68e0973fc13836cc8077f6071dafac888a335 (@varl).  For starters we should definitely strip the logging.

More importantly though we need to **investigate why the HeaderBar is re-rendering every time something unrelated on the page changes**.  I am seeing this behavior during an Analytics Table Export which is polling for job status every 10 seconds.  The HeaderBar re-renders with each update, even though it doesn't need to.  I imagine a lot of other components are re-rendering unnecessarily as well!

<img width="1392" alt="screen shot 2018-10-08 at 6 21 57 pm" src="https://user-images.githubusercontent.com/947888/46621501-e8851900-cb27-11e8-8d05-4878f23b6f07.png">

**Comment by varl** [comment]
I added the logging for another reason, but I left them in to expose the problem of the header bar re-rendering countless times for arbitrary reasons, as a constant reminder that we need to look into it.

I guess that didn't pan out and we became blind to the insanity instead. 👎

**Comment by varl** [comment]
Resolved.
