### ISSUE TITLE
Add isPositiveNumber validator

### ISSUE THREAD

**Issue by nicolayr** [dhis2/d2-ui#36]
We need a validator that only accepts positive numbers, eg. for the [standard deviation setting](https://github.com/dhis2/settings-app/issues/38).

**Comment by adhbh** [comment]
Fixing this. Also writing tests.

 validators: ['positive_number'], is fine right? or do you want validators: ['number', 'positive'] ?

**Comment by nicolayr** [comment]
Great, thank you :+1:

`positive_number` is fine
