### ISSUE TITLE
Get 100% test coverage

### ISSUE THREAD

**Issue by nicolayr** [dhis2/d2-ui#37]
Currently at about 75%

**Comment by Markionium** [comment]
It's a bit of an inflated 75%. The real number is likely somewhat lower.

The (unfortunately) way the coverage checker currently works is that it only checks coverage on files that actually have tests run on them. 

The `Sidebar` component (for example) does not have any tests run against it, so this is excluded from coverage. The coverage there is thus 0%, this is however not counted in the statistics... ;) 

So not only do we need to get the % up, we also need to create test files for the missing pieces.

**Comment by nicolayr** [comment]
Indeed. I already added empty tests for `FormBuilder` to get it included in the coverage stats. Will do the same for `Sidebar`.
