### ISSUE TITLE
[DataTable] Displays empty context menu if there are no options

### ISSUE THREAD

**Issue by nicolayr** [dhis2/d2-ui#52]
To reproduce, simply create a `DataTable` and don't specify the `contextMenuActions` prop. If you right click on a row, or click the context menu icon on the right, an empty context menu pops up.

**Comment by shiveeg1** [comment]
@nicolayr This is how I'm thinking to fix the bug. Please confirm if the workflow is ok. 

Pass another prop to the DataTableRow component from the DataTable.component containing boolean value true if the this.props.contextMenuAction === undefined eg 
                             ` isEmpty_cma = if(this.props.contextMenuAction === undefined)`
and not render the <IconButton> component if this prop is true.  
Also set state showContextMenu = false in the handleRowClick() method and check for this state before calling renderContextMenu()

Does this sound about right ?

**Comment by nicolayr** [comment]
Hi @shiveeg1 - you got the right idea, but it would be more elegant to do it without changing the API of the components. Instead of passing a new prop, you can just check if there are any context menu items to display.

Also keep in mind that the `contextMenuActions` prop can be either `undefined` or an object, but the context menu should only be displayed if the object actually contains at least one item.

**Comment by shiveeg1** [comment]
@nicolayr I fixed the bug by checking at least one item exists in `ContextMenuActions` as you said. I call `renderContextMenu()` only if the condition holds true. I have the expected behaviour.

But test module `DataTable.component.test.js` expects the component to have length at least one, which wouldn't be the case here.
It's line 130 : `expect(contextMenuComponent).to.have.length(1);`

So during commit it fails the test with the following error 

`1) DataTable component interaction should show the context menu when the activeRow state is set:
     AssertionError: expected { Object (root, unrendered, ...) } to have a length of 1 but got 0
      at Context.<anonymous> (DataTable.component.test.js:130:50)`

Should I change the test file or there is an alternative approach to this ?

**Comment by nicolayr** [comment]
When you change a component, it will almost always be necessary to change the tests as well.

Depending on what changes you've made, that can mean both removing tests that are no longer relevant and modifying tests that are no longer correct. It also usually means you should add new tests to ensure that the newly added functionality doesn't break when we make changes to the component in the future.

If we were able to perfectly predict everything we will need in the future, we could _start_ by writing lots and lots of unit tests. Then we would start writing the code for the functionality itself, and when all the unit tests pass we would be ready to release version 1.0.0. In practice however it's a much more iterative process where we continuously discover that we need functionality that we didn't anticipate. This is a good example of that: We didn't anticipate ahead of time that we'll need data tables without context menu actions.
