### ISSUE TITLE
[OUTree/TreeView] Compact flag?

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2-ui#56]
It might be worth to allow a more compact version of the tree that removes the margin before the children. Perhaps we should allow the user to determine which "version" to use. The more compact tree could be used in places where the real estate on the screen is smaller. (Which obviously relates to the question if putting a tree there is a good idea in the first place :))

Current:
![image](https://cloud.githubusercontent.com/assets/2134901/14377422/cf51a6b6-fd6f-11e5-8531-7a1f84427611.png)

Compact:
![image](https://cloud.githubusercontent.com/assets/2134901/14377410/c23b6e3a-fd6f-11e5-9377-1adbc56e934e.png)

**Comment by nicolayr** [comment]
I didn't put a lot of thought into the margin, I just picked something that worked ok for the examples and never really had a reason to fine tune it. So unless there's a reason why we need both versions, I suggest we just keep it simple and decrease the default margin in the `TreeView` component.

**Comment by nicolayr** [comment]
Of course, passing down a style prop is also an option, but the simpler the API of the components are the better :)

**Comment by Markionium** [comment]
Fair enough, agreed. Then lets keep the compact version as default :)
