### ISSUE TITLE
Question <HeaderBar/> default UI?

### ISSUE THREAD

**Issue by vivekdtiwari** [dhis2/d2-ui#63]
As a trial, similar to other examples in repo I created a simple example to try out something basic in d2. I managed to get the example working correctly, however the UI of HeaderBar where apps/username is displayed looks very weird and there were no errors though. It looks as follows : 
![headerbar](https://cloud.githubusercontent.com/assets/9805866/14934328/146741a4-0ecb-11e6-81e3-a9c52158c07b.png)

I am aware that in settings-app the styling is explicitly defined before <HeaderBar/> component is called. However curious to know if there exists a default UI css? or why does the app list on right look so weird? Is this the expected behaviour?

Rough code I used : (js file) 
```
import React from 'react';
import {render} from 'react-dom';
import {init} from 'd2/lib/d2';
import HeaderBar from '../../src/header-bar/HeaderBar.component';

import injectTapEventPlugin from 'react-tap-event-plugin';
injectTapEventPlugin();

jQuery.ajaxSetup({
    headers: {
        Authorization: 'Basic ' + btoa('admin:district'),
    },
});


init({baseUrl: 'http://localhost:8082/api'}).then(renderExamples);


//my tests start here.
function renderExamples(d2){
  var Kk = React.createClass({
    propTypes : {
      d2 : React.PropTypes.object.isRequired,
    },
    childContextTypes : {
      d2 : React.PropTypes.object,
    },
    getChildContext(){
      return {
        d2 : this.props.d2
      }
    },
    render(){
      return (
        <HeaderBar/>
      )
    }
  })
  render(<Kk d2={d2}/>,document.getElementById('header-bar'))
}


function renderIconPicker() {
    render(
        <HeaderBar/>
        , document.querySelector('#header-bar'));
}

```

HTML file.
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Testing HeaderBar</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>
  <body>
  <div id="header-bar"></div>
  <h1 style="margin-top:100px"><a href="index.html">D2-UI Examples</a>: Data Table component</h1>
  <hr/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="header-bar.js"></script>
  </body>
</html>

```

**Comment by adhbh** [comment]
You will need to import scss file from d2-ui in your project's scss
`@import "../node_modules/d2-ui/scss/HeaderBar"`

You can then use tools like node-scss to compile .scss files to css.

**Comment by vivekdtiwari** [comment]
![image](https://cloud.githubusercontent.com/assets/9805866/14934536/8c6509f2-0ed0-11e6-8c03-b34fe78fefe3.png)
@adhbh Thanx for the info.
After doing require('d2-ui/scss/HeaderBar.scss');
I got it to work. Little difficult to get started. So including the styling explicitly is needed for correct component UI. Doubt cleared so closing this.

**Comment by Markionium** [comment]
@vivekdtiwari Agreed that this is a bit confusing. Its partially due to the fact that we had to integrate the "legacy" headerbar wrapped by a React component. 

For dhis2 2.24 we are rewriting the headerbar from scratch and integrating some additional search functionality, to search the contents of apps directly (say search for specific settings from within the headerbar, or search for parts of the maintenance app from the headebar such "indicator" or "data element")

Will make sure it'll be easier to integrate ;)
