### ISSUE TITLE
HeaderBar

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2-ui#66]
- [x]  Remove the x by x icon/selector
- [x]  Move the icons a little bit to the left
- [x]  ~~Change placeholder text from "Super search.." to "Search for anything".~~ (Changed to Search apps as it currently only relates to apps)
- [x]  Include a magnifier icon for the search on the right end of the search field (not because anyone will click it but to indicate that it is a search field, google/fb style)
- [x]  Make the search field/drop menu max-width 700 px
- [x]  Use pointer hand mouse icon instead of text input
- [x]  Light grey background on hovered menu icon
- [x]  Bit more spacing on top of "MORE APPS" link
- [x]  ~~Use regular case "More apps" for link~~ (This is default google material behaviour)
- [x]  ~~Show unread message badge~~ (Not for 2.24)
- [x] ~~Close search results on "Esc"~~
- [x] ~~Add fallback translations for languages other than English~~ Server translations take care of this.
- [x] Access control for header-bar items from maintenance-app
- [x] Close when clicking on links within the search results (This impacts the maintenance app as the menu clicks there are in app)
- [ ] When focus is lost from the search field through a click inside the results and moving outside of the search results they don't close.
- [x] Use the dynamic link for help when it is available
- [x] X to clear the search field when it has a value
- [x] 4 X 3
- [x] ~~Allow title full with, search field overlaps~~ (Title will break using ellipsis when it is too long. The tested with with the tested title is 1300. See screenshots below)
- [x] In app items need app's permission to view (if it is in the apps list then allow in app stuff)
- [x] Show app for in app items as the last item

**Comment by Markionium** [comment]
The initial idea of having the searchbar slide over the title, was not very nice. It looked like the headerbar consists of two overlapping layers (when the title is partially hidden) instead of a single one. An alternative could be to hide the title when the searchbar is open.

![image](https://cloud.githubusercontent.com/assets/2134901/15984569/0237c2ac-2fd1-11e6-8b77-27e85a862612.png)

Menu will scale to 3x3 icons when there is not enough screen width
![image](https://cloud.githubusercontent.com/assets/2134901/15984574/1d97dbf4-2fd1-11e6-8ca5-2db3e22a7a24.png)

Title will truncate when space is even smaller
![image](https://cloud.githubusercontent.com/assets/2134901/15984580/3fd7d886-2fd1-11e6-8ff0-5dd2918352a9.png)

Title will be gone when there is almost no space left
![image](https://cloud.githubusercontent.com/assets/2134901/15984577/31101e6c-2fd1-11e6-81c5-a587a4a8a190.png)

It might be worth hiding the logo when the screen space becomes even smaller, as the following looks kind of strange.
![image](https://cloud.githubusercontent.com/assets/2134901/15984586/62c994f6-2fd1-11e6-9eea-2cde64784fe1.png)

**Comment by nicolayr** [comment]
Closing this since we're about to start a new testing cycle and all but 1 sub-item were closed already ;)
