### ISSUE TITLE
Create legend component

### ISSUE THREAD

**Issue by turban** [dhis2/d2-ui#71]
We're moving the legend component from the GIS app to the Maintenance app, and it will be improved by predefined color scales from ColorBrewer (widely used for mapping applications). It is kept in d2-ui to allow reuse. 

Remaining issues: 
- [x] Set max number for decimals for class breaks.
- [x] Start and end values should be required (before clicking "Create legend items").
- [x] Set default color for new legend items. 
- [x] Add cancel button when editing legend items. 
- [x] Create separate dialog for the color picker to make it easier see the selected color (create a new color component). 
- [ ] Add gaps in legend validators and overlapping legends. (This might need to go into the maintenance app, or at least integrate with https://github.com/dhis2/maintenance-app/blob/master/src/config/field-overrides/legendSet.js)
- [ ] Tests

Styling:
- [x] Extra space above list of legend items. 
- [x] Fields with error messages should still be aligned.

**Comment by Markionium** [comment]
@turban Saving seems to work correctly with the current api.

It is possible to send a LegendSet with a list of legends and it will replace the items. I had to make some small adjustments to how we save models to make it send the full "legend" properties with the LegendSet. https://github.com/dhis2/d2/commit/86a4088af0f258be28a44aedcf52406a7f8335e1

I also asked @mortenoh to add the authorities to the schemas endpoint. That should make the add button show up when the add authority is available.

Something to note might be that when saving LegendSets this way we probably end up with a bunch of "orphaned" Legend objects that do not belong to any LegendSet. But perhaps that is taken care of somehow already ;)

I have not yet added the legend gap/overlapping validators, so will add that to the todo list above.

**Comment by turban** [comment]
@larshelge - is it possible to avoid "orphaned" legend items? Wouldn't it be much better to save a full legend, I don't see any use cases for individual legend items (color/name pair). 

@Markionium - in which file could I add the gap/overlapping validators? 

I would also like to change the names we use. I'm not used to "Legend Sets" consisting of "Legends". 
A "Legend set" is simply a "Legend". A legend consists of colors, items or classes. 

"A map legend is included with a map to unlock it. It gives you the information needed for the map to make sense. Maps often use symbols or colors to represent things, and the map key explains what they mean. Map keys are often boxes in the corner of the map, and the information they give you is essential to understanding the map. Symbols in the key might be pictures or icons that represent different things on the map. Sometimes the map might by colored or shaded, and the key explains what the colors and shades mean."

**Comment by turban** [comment]
This is about as far I get before the 2.24 release, as I need some assistance from @Markionium and @mortenoh to finish it. 

This is the status:

Most of the code is in d2-ui to allow reuse later in the GIS app: 
https://github.com/dhis2/d2-ui/tree/master/src/legend

Unfortunately, there are no tests yet - I'm happy to add them later after the release ;-)

Legend sets are available in the maintenance app (in master branch, not yet published to trunk): 

![screen shot 2016-06-14 at 14 17 14](https://cloud.githubusercontent.com/assets/548708/16042424/deb7f70e-323a-11e6-8e26-a05377feb831.png)

As I understand a schema change from @mortenoh is required for the + button to show up. 

Legend sets can currently be accessed by adding the id to the URL: http://localhost:8081/#/edit/otherSection/legendSet/fqs276KXCXi

![screen shot 2016-06-14 at 14 22 42](https://cloud.githubusercontent.com/assets/548708/16042537/7edfed68-323b-11e6-8f3b-e854d8ed2c05.png)

New legends can now be created my selecting start and end values, number of classes/items and a predefined color scale:

![screen shot 2016-06-14 at 14 25 24](https://cloud.githubusercontent.com/assets/548708/16042650/13722f04-323c-11e6-90ec-bb67cba72f0b.png)

We're showing a warning as this will replace all current legend items: 

![screen shot 2016-06-14 at 14 27 39](https://cloud.githubusercontent.com/assets/548708/16042701/462769fa-323c-11e6-9145-f7ed146b8d7f.png)

There are validity checks on the data:

![screen shot 2016-06-14 at 14 28 56](https://cloud.githubusercontent.com/assets/548708/16042738/7c8c9d62-323c-11e6-80e0-4c68b9e742bc.png)

This will automatically create a color scale:

![screen shot 2016-06-14 at 14 31 19](https://cloud.githubusercontent.com/assets/548708/16042772/c053e514-323c-11e6-8c69-99527b5d8624.png)

We leave "name" empty as default is to show the start - end value. 

Individual legend items can be deleted, edited and added: 

![screen shot 2016-06-14 at 14 34 30](https://cloud.githubusercontent.com/assets/548708/16042877/3251f17e-323d-11e6-9997-1ed6e0fdbe05.png)

You need to decide if it is possible to include this in 2.24. If so, remember to remove the Legend sets from the GIS app!

**Comment by turban** [comment]
@Markionium, In the [legendSet.js](https://github.com/dhis2/maintenance-app/blob/master/src/config/field-overrides/legendSet.js) file, how can I loop thorough the items/models to do a validity check before saving? 

I've also commented out two validity checks in LegendItem.store.js:
https://github.com/dhis2/d2-ui/blob/master/src/legend/LegendItem.store.js

These two checks are linked, if one is true, the other is also true - but if the user fixes one - only the associated warning is removed - and not the other. Is it possible to fix somehow?
