### ISSUE TITLE
[OrgUnitTree]  Border around tree

### ISSUE THREAD

**Issue by larshelge** [dhis2/d2-ui#75]
For the org unit tree, add a border around the tree. This to emphasize the tree widget area. Should look something like the mockup attached.

![tree](https://cloud.githubusercontent.com/assets/908206/17781392/719b6ec2-656f-11e6-8442-5b5b7e007cbb.png)

**Comment by nicolayr** [comment]
This is an implementation detail in the maintenance app, and has been addressed in  https://github.com/dhis2/maintenance-app/commit/a3b9c8e9838b7b01f8bfea0213c3cc1339ad0a06
