### ISSUE TITLE
[OrgUnitTree] POST diff of selected org units

### ISSUE THREAD

**Issue by larshelge** [dhis2/d2-ui#91]
For the org unit tree, the diff (newly selected or deselected org units) should be posted to the Web API. This as opposed to posting all selected org units as is the current behavior.

See [docs](https://dhis2.github.io/dhis2-docs/master/en/developer/html/webapi_metadata_crud.html#webapi_adding_removing_objects_collections) under "1.10.4.3. Adding and removing objects in a single request" for how to add and remove org units in a collection like data sets.

**Comment by nicolayr** [comment]
Moved to the maintenance app issues list: https://github.com/dhis2/maintenance-app/issues/264
