### ISSUE TITLE
Stop header bar cache buster from causing stack trace on the server

### ISSUE THREAD

**Issue by nicolayr** [dhis2/d2-ui#92]
Don't send a number that causes Integer overflow.

**Comment by nicolayr** [comment]
Backport to 25 and 24 (and 23?)

**Comment by Markionium** [comment]
Just 24 should be sufficient (unless it's a trivial thing for 2.23, but doubt it, since there we still used the old header-bar)

**Comment by nicolayr** [comment]
Fixed in https://github.com/dhis2/d2-ui/commit/8b50f3d180a8fcded25f1542b882951bc2ba8d90

**Comment by Markionium** [comment]
This is fixed but apps will need to be re-deployed.
